### ISSUE TITLE
GitHub link for DefinitelyTyped changed

### ISSUE THREAD

**Issue by FelipeCostaGualberto** [Zlatkovsky/BuildingOfficeAddins#23]
On page 41, there is a link to download a JS file (DefinitelyTyped), but apparently the URL for the file changed.

Old link:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/office-js/index.d.ts

New link:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/office-js/index.d.ts

**Comment by Zlatkovsky** [comment]
@FelipeCostaGualberto , yep, just discovered it myself this morning.  Will fix, and also include a suggestion to just use '@types/office-js', which sidesteps the problem altogether
