### ISSUE TITLE
Stocks Example

### ISSUE THREAD

**Issue by syncimprov** [Zlatkovsky/BuildingOfficeAddins#46]
The REST query to yahoo does is not working out-of-the-box. Changed the URL as follows to get it to work. FYI.

```
    var data = 'q=' +
        encodeURIComponent(
            'select * from yahoo.finance.quote ' +
            'where symbol in (' + quotedCommaSeparatedNames + ')'
        ) +
        "&env=store%3A%2F%2Fdatatables.org" +
        "%2Falltableswithkeys&format=json";
```

**Comment by Zlatkovsky** [comment]
OK, thanks for letting me know.  I wonder if they'd changed something, since I promise it did once work :-)
Making the change now, will go out with the next update.
