### ISSUE TITLE
Contradiction regarding return value of objects (p106 and p147)

### ISSUE THREAD

**Issue by hishamjaber** [Zlatkovsky/BuildingOfficeAddins#64]
On page 106, the text says that the return value of object.load(...) is the object itself and that:
     `let range = worksheet.getRange("A1").load("values");`
is 100% equivalent to:
    `let range = worksheet.getRange("A1");`
    `range.load("values");`

Whereas on page 147, the text says that method invocations always return a new object and that:
    `context.workbook.getSelectedRange().load("address");`
will return an error, where in fact it does not.  It works perfectly fine.

**Comment by Zlatkovsky** [comment]
@hishamjaber , the information on page 106 is correct.

The info on page 147 is *also* correct, but I think you misread it.  What I was trying to say is that anytime you call a `get<XYZ>` method, you get a new fresh object, which has no loaded properties on it.  Thus, `context.workbook.getSelectedRange().address` is *always* going to throw a `PropertyNotLoaded` error.  In order for that code to be correct, you would need to instead save off the first line into a variable, e.g., `var range = context.workbook.getSelectedRange().load("address");`.  And then, after an `await context.sync()`, you would be able to do `console.log(range.address)` just fine.

Does that make sense?

**Comment by hishamjaber** [comment]
Yes, I see that now.
Thank you so much for taking the time to write the book.

**Comment by Zlatkovsky** [comment]
My pleasure.
