### ISSUE TITLE
[Content issue]: Incorrect statement in "Implementation Details" section

### ISSUE THREAD

**Issue by GabRoyer** [Zlatkovsky/BuildingOfficeAddins#9]
In this section, you say that when a method or property gets called on a proxy, either an object path is created or an action, but that is not correct. All property access and method call create a new action, which operates on a object and may or may not create another object, which would then get assigned its object path.

**Comment by Zlatkovsky** [comment]
Fixing in forthcoming 1.2 iteration of the book.
